set PATH=.;%PATH%
set CURR_DIR=%CD%
set PATH=%UNITZ_HOME%;%PATH%
set PYTHONPATH=%PYTHONPATH%;%CURR_DIR%\lib
set PYTHONPATH=%PYTHONPATH%;%CURR_DIR%\config
set PYTHONPATH=%PYTHONPATH%;%CURR_DIR%\std_units
set PYTHONPATH=%PYTHONPATH%;%CURR_DIR%\tests
set PYTHONPATH=%CURR_DIR%;%PYTHONPATH%

set PYTHONPATH=%PYTHONPATH%;%UNITZ_HOME%\lib
set PYTHONPATH=%PYTHONPATH%;%UNITZ_HOME%\config
set PYTHONPATH=%PYTHONPATH%;%UNITZ_HOME%\std_units
set PYTHONPATH=%PYTHONPATH%;%UNITZ_HOME%\tests
set PYTHONPATH=%UNITZ_HOME%;%PYTHONPATH%

set PYTHONPATH=.;%PYTHONPATH%
