#!/usr/bin/env python

## The launch command for unitz

from __future__ import print_function
import unitz.commands
import sys

if __name__ == "__main__":
    if len(sys.argv[1:]) < 1:
        unitz.commands.help(None)
        exit(1)

    cmd = sys.argv[1]
    cmdargs = None
    if len(sys.argv[2:]) > 0:
        cmdargs = sys.argv[2:]
    if not unitz.commands.executeCommand(cmd, cmdargs):
        exit(1)

    exit(0)
